Homework2
pitoner/homework-repository pull request #5
Opened 2021-04-19 17:58 UTC by pitoner

2021-04-21 17:49 UTC, i-n-samartsev commented on homework2/hw1.py
> +        for extra_char in punctuation + digits + "‹›—«»":
для подобной операции у строк есть функция .translate()

2021-04-21 17:50 UTC, i-n-samartsev commented on homework2/hw1.py
> +    with open(file_path) as fin:
кодировку можно сразу указать в open()

2021-04-21 17:53 UTC, i-n-samartsev commented on homework2/hw1.py
> +            yield bytes(line, "ascii").decode("unicode-escape")
если тебе приходится конвертировать строку в байты а потом обратно в строку - это должно было тебя уже насторожить. в таком случае вообще было бы правильно открывать файл в бинарной форме (чтобы сразу байтстроки читать). а вообще правильно, как я указал выше, использовать параметр кодировки при открытии файла. + если кодировка нестандартная, обычно ее надо указывать параметром (со значением по-умолчанию utf-8, потому что по стандарту это именно кодировка по умолчанию).
оффтопик: Если интересно, в модуле io есть довольно много разных интересных классов как можно оборачивать байтовое чтение в строковое, добавлять буферизацию, и тд. покопайся, лишним не будет.

2021-04-21 17:54 UTC, i-n-samartsev commented on homework2/hw1.py
> +                        top_ten_words[index] = (len(word), word)
6 уровней вложенности! должен звонок в голове прозвенеть что что-то не так

2021-04-21 18:02 UTC, i-n-samartsev commented on homework2/hw1.py
> +            line = line.replace(extra_char, "")
тут ты склеиваешь все слова в одно, это ошибка.

2021-04-21 18:08 UTC, i-n-samartsev commented on homework2/hw1.py
> +        read_title_counter = 0
нельзя затачивать реализацию под конкретный файл. если в тесте будет файл без заголовка? в крайнем случае надо указать параметр, сколько строк надо "спецобработать". но в этом задании это не нужно. убери спецобработку заголовка. все должно решиться грамотным открытием файла.

2021-04-21 18:16 UTC, i-n-samartsev commented on homework2/hw1.py
> +                        top_ten_words[index] = (len(word), word)
есть довольно простой способ как обходиться без большого количества висячих вложенностей.
например вместо 

               if len(set(word)) > shorter_top_ten_word_length:
                   ...
                   
можно проверять негативный кейз

            if len(set(word)) <= shorter_top_ten_word_length:
                 continue
                 
 тогда вместо сильно ветвящегося алгоритма у тебя получается линейная последовательность проверок, которая лучше воспринимается

2021-04-21 18:20 UTC, i-n-samartsev commented on homework2/hw1.py
> +                        top_ten_words[index] = (len(word), word)
можно обойтись без enumerate и содержания данных в виде кортежей.
попробуй конструкцию
   longest_words = [""] * 10  # 10 pre-sorted longest encountered words
   for word in all_your_words:
       if len(word) < len(longest_words[0]):
          continue
       longest_words.append(word)
       longest_words = sorted(longest_words, key=lambda a: len(a))[1:]  # maintaining the sortedness

2021-04-21 18:24 UTC, i-n-samartsev commented on homework2/hw1.py
> +            if char in punctuation:
тут и в других  местах проблема - из модуля string наборы символов пунктуации, вайтспейсы - только ascii-шные. у тебя тут файл юникодовый (правда в спецкодировке). Правильно тут использовать на проверку на категорию символа модуль unicodedata и фнукцию которая возвращает категорию юникод символа. и проверяй потом, если категория начинается на P - это пунктуация, если на L - буква, и тд. полный список категорий тут https://en.wikipedia.org/wiki/Unicode_character_property#General_Category

2021-04-21 18:30 UTC, i-n-samartsev commented on tests/homework2/hw1_test.py
> +    """Generator for monkeypatching read_ascii_file"""
1) правильнее было бы писать во временный файл, созданный модулем tempfile, и передавать тест-функции  уже имя файла, чтобы его открыть. исправь.
2) добавь еще тесты
  - текст без заголовка
  - текст не в кодировке unicode-escape а в обычном utf-8
  - тесты для разных функций должны иметь собственные наборы данных, специфичные для них. например, тестируя подсчет пунктцации ты можешь создать кейс где файл только с символами пунктуации, вперемешку со словами, на одной строке или нескольких и тд.

2021-04-21 18:33 UTC, i-n-samartsev commented on homework2/hw2.py
> +    most_common = least_common = uniq_obj, inp.count(uniq_obj)
вызвав .count() ты потерял весь смысл взятия итератора по входным данным, так как входная последовательность будет перебрана.

2021-04-21 18:39 UTC, i-n-samartsev commented on homework2/hw2.py
> +    most_common = least_common = uniq_obj, inp.count(uniq_obj)
если ты и так готов вызывать .count() на каждый элемент, просто отсортируй входящие данные по ключу встречаемости. а еще лучше - перебери эти элементы и подсчитай сам в один проход.

2021-04-21 18:46 UTC, i-n-samartsev commented on homework2/hw3.py
> +                            [list1_elem, list3_elem, list2_elem],
>>> combinations([1], [2], [3])
[[1, 2, 3], [1, 3, 2]]

второй пары быть не должно.

2021-04-21 18:49 UTC, i-n-samartsev commented on homework2/hw3.py
> +    return _combinations(_combinations(*args[: k // 2]), _combinations(*args[k // 2 :]))
неверно.
>>>combinations([1], [2], [3], [4], [5], [6])
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 6, 5], [1, 3, 2, 4, 5, 6], [1, 3, 2, 4, 6, 5]]

а должно получаться [[1,2,3,4,5,6]]

2021-04-21 18:51 UTC, i-n-samartsev commented on homework2/hw3.py
> +    return _combinations(_combinations(*args[: k // 2]), _combinations(*args[k // 2 :]))
совет - изложи свой алгоритм языком, дословно, и переводи его в питон переводом на английский. старайся чтобы этот алгоритм был понятен ребенку 5 лет. начинай сначала с написания тестов до реализации, так избежишь алгоритмических ошибок.

2021-04-21 18:54 UTC, i-n-samartsev commented on homework2/hw3.py
> +        while len(combo) != len(args):
не понял секцию с 51 по 56 строки. тут ты фактически делаешь так
while len(combo) != len(args):
   combo = list(combo)

есть подозрение что этот код вообще не выполняется

2021-04-21 18:57 UTC, i-n-samartsev commented on homework2/hw4.py
> +            cache_args[args] = func(*args)
не будет работать если в качестве параметра передать например список
 
    @cache
    def f(a):
       return a

    f(['test'])   # will raise an error

2021-04-21 19:22 UTC, i-n-samartsev commented on homework2/hw5.py
> +    _arg1=None,
дублировать аргументы не надо . у тебя всего 3 аргумента, которые отвечают за логику выборки = начальная позиция, конечная позиция и шаг. пусть они и остаются
    def custom_range(iterable, start, stop, step)
каждый из этих аргументов может быть вызван как позиционный и через ключевое слово. обязанность правильно указать аргументы при вызове - обязанность вызывающего а не автора функции. достаточно что ты их описал в сигнатуре и в докстринге.

2021-04-21 19:27 UTC, i-n-samartsev commented on homework2/hw5.py
> +    start, stop, step = _check_arguments(_arg1, _arg2, _arg3, start, stop, step)
давай я напишу тебе алгоритм на словах для реализации.

если шаг положительный то будем перебирать входящую последовательность в восходящем направлении с начала. перебирать будем iterable.
если шаг отрицательный, то в нисходящем с конца. перебирать будем reversed(iterable)

в процессе перебора:
   пока не встретился стартовый символ ничего не делаем
   если встретился стартовый символ, выводим его и далее каждый символ кратный шагу
   если встретился конечный символ прекращаем перебор

2021-04-21 19:29 UTC, i-n-samartsev commented on homework2/hw5.py
> +    while True:
никогда так не делай, делай так:

    for element in iterable:
       ...

2021-04-21 19:31 UTC, i-n-samartsev commented on homework2/hw5.py
> +        iterable = _get_reversed_short_iter(iterable, start, stop)
просто reversed(iterable)

2021-04-21 19:32 UTC, i-n-samartsev commented on homework2/hw5.py
> +    step=None
step по умолчанию можно поставить 1
это тебе уберет как минимум одну проверку дальше

2021-04-21 19:33 UTC, i-n-samartsev commented on tests/homework2/hw5_test.py
> +    for elem in ["a", "b", "c", "d", "e", "f"]:
как проверять правильно обсудили в телеге

2021-04-21 19:34 UTC, i-n-samartsev requested changes
исправь согласно комментариям + разберем правильный подход на практике

2021-04-22 12:53 UTC, pitoner commented on homework2/hw5.py
> +    _arg1=None,
Если указать
`def custom_range(iterable, start, stop, step)`
То я не пройду следующий тест
```
assert = custom_range(string.ascii_lowercase, 'g') \
== ['a', 'b', 'c', 'd', 'e', 'f']
```

2021-05-06 18:52 UTC, i-n-samartsev commented on homework2/hw1.py
> +def open_file(func: Callable) -> Callable:
это лишний декоратор. достаточно было просто добавить параметр encoding='utf-8' и прокидывать его в опен. А тут ты уже существенно поменял сигнатуры вызовов целевых функций.
def get_longest_diverse_words(file_input: TextIO)-> List[str]
очень сильно отличается от сигнатуры  (и при этом обратно несовместимо)
def get_longest_diverse_words(file_path: str) -> List[str]
а вот такой подход будет расширением существующей сигнатуры
def get_longest_diverse_words(file_path: str, encoding='utf-8') -> List[str]

2021-05-06 18:53 UTC, i-n-samartsev commented on homework2/hw1.py
> +def open_file(func: Callable) -> Callable:
убери декоратор и добавь параметр encoding со значением по умолчанию utf-8

2021-05-06 18:55 UTC, i-n-samartsev commented on homework2/hw1.py
> +    while True:
тут можно использовать моржовый оператор

```
while symbol := file_input.read(1):
   ...
```

2021-05-06 18:55 UTC, i-n-samartsev commented on homework2/hw1.py
> +    while True:
и везде далее по тексту аналогично

2021-05-06 18:59 UTC, i-n-samartsev commented on homework2/hw1.py
> +def tokenizer_char_type(file_input: TextIO) -> Generator[Tuple[str, str], None, None]:
а нужен ли этот токенизатор вообще? ты же можешь напрямую читать из файла посимвольно всегда. 
"токен" это не обязательно пара (тип-значение), это просто "какой-то элемент текста". то есть если тебя устраивает стандартное посимвольное чтение, это тоже можно использовать.

2021-05-06 18:59 UTC, i-n-samartsev commented on homework2/hw1.py
> +def tokenizer_char_isascii(
И снова вопрос - нужен ли этот конкретный токенизатор если ты не разбиваешь входной файл на элементы?

2021-05-06 19:08 UTC, i-n-samartsev commented on homework2/hw1.py
> +def open_file(func: Callable) -> Callable:
в результате получится конечно то же самое что и сделал ты (только без декоратора), но будет более читаемо, понимаемо и документируемо

2021-05-06 19:10 UTC, i-n-samartsev commented on tests/homework2/hw1_test.py
> +@pytest.mark.parametrize("encoding", ["utf-8", "unicode-escape"])
у тебя повторяется одинаковая параметризация на целую кучу тестов, и при этом она тестирует фактически кейс если я сохраняю файл в определенной кодировке, то указывая эту кодировку в параметре, используется именно она. 
Тут лучше вместо параметризации проверять этот кейс отдельно.
параметризация штука теоретически хорошая, но запутывает код очень сильно. лучше пользоваться ей редко и точно зная зачем это делая.

2021-05-06 19:12 UTC, i-n-samartsev commented on homework2/hw2.py
> +    most_common = max(elements, key=lambda elem: elements[elem])
тут можно отсортировать один раз и взять [0] и [-1]

2021-05-06 19:15 UTC, i-n-samartsev commented on homework2/hw3.py
> +def combinations(*args: List[Any], deep: int = 0) -> List[List]:
что за аргумент deep, почему он не описан?

2021-05-06 19:42 UTC, i-n-samartsev approved these changes

2021-05-08 08:38 UTC, merged