Homework4
pitoner/homework-repository pull request #7
Opened 2021-04-28 07:43 UTC by pitoner

2021-05-09 19:28 UTC, i-n-samartsev commented on .github/workflows/main.yml
> +          pip install black isort pytest requests
тут правильно было бы создать файл requirements.txt и ставить все из него вместо того чтобы перечислять все в ci.

2021-05-09 19:34 UTC, i-n-samartsev commented on tests/homework4/test_task_1_read_file.py
> +def test_read_magic_number_file_doesnt_exist_error():
Раз тема про написание и грамотное оформление тестов, давай немного подправим как ты именуешь и документируешь код.
- Укороти название функции, такие длинные имена обычно показывают что ты что-то делаешь неправильно. тут можно было назвать так test_file_not_exists и все было бы понятно (а детали вынести в докстринг). Если же тебе надо прям кровь из носу указать например что это тест для read_magic_number  - можно вынести эту группу тестов в подмодуль. было бы не tests.homework4.test_task_1_read_file.py а tests.homework4.task1.read_magic_number.test_blahblahblah.py - никогда не забывай что ты в любое время можешь переструктурировать свой проект и что-то куда-то перенести. Постарайся делать это побольше, это поможет в дальшейшем научиться быстро и эффективно рефакторить свой и чужой код.
- Докстринги! не забывай документировать код. Для тестов это практически обязательная штука, в докстринге ты можешь словами описать что ты тестируешь и как, фактически описать тесткейз.

2021-05-09 19:49 UTC, i-n-samartsev commented on homework4/task_2_mock_input.py
> +def count_dots_on_i(url: str) -> int:
В этом задании я хочу рассказать что такое "сервисные классы" и как они облегчают тестирование. Если нужна дополнительная информация пиши в телегу, договоримся созвониться - объясню.
Сравни такие два подхода
- функция которая несет нагрузку с бизнес-логикой (посчитать символ i из какого-то третьего источника) также сама занимается реализацией запросов на внешний сайт.
- Функция которая несет нагрузку с бизнес логикой занимается только бизнес-логикой и интеграцию с третьим источником отдает на откуп отдельному классу (и тестировать его отдельно). В тестах функции с бизнес-логикой мы считаем что класс уже протестирован и тогда мок становится довольно приятный.
предположим мы тащим из интернета погоду

```
class WeatherClient:
   def __init__(self, website):
       self.website = website
   def get_weather(self, city):  # реализацию писать не буду, это для примера
       ...
   
```    
def business_logic():
    client = WeatherClient('https://gismeteo.ru')
    if client.get_weather('Saint-Petersburg') < Storage().get_old_weather(date=year_ago):
        raise 'А говорили глобальное потепление будет, опять лапша на уши'

в таком случае для тестирования business_logic() не надо мокать детали ЧТО возвращает сайт (на это в принципе по барабану, для этого будут отдельно тесты на WeatherClient. А для мока WeatherClient достаточно вот такого простого подменялова класса WeatherClient

```
class FakeWeatherClient:
    def __init__(self, *args, **kwargs):
        pass
        
    def get_weather(self, city):
        return -66
    
```     
 Если какая-нибудь параметризация нужна, то можно создавать такой класс на лету в функции например (это называется фабрикой).
 
 В целом такой подход позволяет отделить бизнес-логику от логику интеграции с другими компонентами, и применятся вообще везде.

2021-05-09 19:55 UTC, i-n-samartsev commented on homework4/task_5_optional.py
> +    while n:
очень не по-питонистски использовать циклы как while c инкрементом\декрементом
используй for i in range(n):

2021-05-09 19:57 UTC, i-n-samartsev commented on tests/homework4/test_task_2_mock_input.py
> +def test_task_2_mock_positive_test():
тесты (и реализацию count_dots_on_i) надо будет переписать на сервисные классы. У тебя будет 2 набора тестов - один на сервисный класс, другой на бизнес-логику.

2021-05-09 19:58 UTC, i-n-samartsev commented on tests/homework4/test_task_3_get_print_output.py
> +def test_my_precious_logger_stdout(capfd):
Напиши в ответе к этому комментарию, как можно реализовать захват вывода в stdout\stderr не используя фикстуры pytest, и в чем будут минусы и плюсы этого подхода.

2021-05-09 19:59 UTC, i-n-samartsev requested changes
Нужно доработать согласно комментариям

2021-05-10 13:06 UTC, pitoner commented on tests/homework4/test_task_1_read_file.py
> +def test_read_magic_number_file_doesnt_exist_error():
Хорошо, исправлю
На занятии по тестам преподаватель сказал, что для тестов докстринги не обязательны, потому что всегда можно написать длинное имя, которое полностью описывает тест и легко читается после запуска pytest'ом

2021-05-12 08:30 UTC, pitoner commented on tests/homework4/test_task_3_get_print_output.py
> +def test_my_precious_logger_stdout(capfd):
Поправьте, если я не прав
В моей функции вывод в лог ошибок реализован так: 
`print(text, file=sys.stderr)`

Фикстура capfd перехватывает вывод на уровне файлового дескриптора. Преимуществом этого способа является, то что мы проверяем почти всю цепочку вывода текста. То же самое можно провернуть с помощью модуля subprocess.

Можно перехватить с помощью фикстуры capsys. В документации написано, что она перехватывает на уровне sys.stderr/sys.stdout. Думаю она просто подменяем sys.stderr/sys.stdout, что можно легко сделать и руками как тут https://stackoverflow.com/questions/4219717/how-to-assert-output-with-nosetest-unittest-in-python/31281467

2021-05-13 11:18 UTC, i-n-samartsev commented on tests/homework4/test_task_1_read_file.py
> +def test_read_magic_number_file_doesnt_exist_error():
это вопрос вкусовщины (как мой, так и лектора), но в мою пользу есть как минимум несколько аргументов
- на длинные имена функций ругаются линтеры и вызывать их при переиспользовании раскорячивает код.
- предназначение имени функции все-таки не описательное, а докстринга - описательное
- докстринги тестовых методов абсолютно идентично показываются питестом в отчете как и имена функций.

2021-05-13 18:43 UTC, pitoner commented on homework4/task_2_mock_input.py
> +def count_dots_on_i(url: str) -> int:
Прошу прощения. Отправляют в командировку срочно, возьму паузу в исправлении до понедельника

2021-05-31 19:40 UTC, i-n-samartsev approved these changes

2021-06-02 15:48 UTC, merged